version: '3'
services:
  shard1:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/shard1:/docker-entrypoint-initdb.d
    command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=1001
    ports:
      - "4001:3306"

  shard2:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql/shard2:/docker-entrypoint-initdb.d
    command: mysqld --log-bin=mariadb-bin --binlog-format=ROW --server-id=1002
    ports:
      - "4002:3306"

  maxscale:
    image: mariadb/maxscale:latest
    depends_on:
      - shard1
      - shard2
    volumes:
      - ./maxscale.cnf.d:/etc/maxscale.cnf.d
    ports:
      - "4006:4006"  # readwrite port
      - "8989:8989"  # REST API port (optional)
