version: '2'
services:
    shard1:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/shard1:/docker-entrypoint-initdb.d
        command: mariadbd --log-bin=mariadb-bin --binlog-format=ROW --server-id=3000
        ports:
            - "4001:3306"

    shard2:
        image: mariadb:latest
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - ./sql/shard2:/docker-entrypoint-initdb.d
        command: mariadbd --log-bin=mariadb-bin --binlog-format=ROW --server-id=3001
        ports:
            - "4002:3306"

    maxscale:
        image: mariadb/maxscale:latest
        depends_on:
            - shard1
            - shard2
        volumes:
            - ./maxscale.cnf.d:/etc/maxscale.cnf.d
        ports:
            - "4000:4000"  
            - "4006:4006"  
            - "4008:4008"  
            - "8989:8989"  
